env:
  - HUGO_VERSION="0.53"

install:
  - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - mv hugo ~/bin/
  - gem install html-proofer --no-ri --no-rdoc

script:
  - cd exampleSite
  - hugo --themesDir ../.. -t chaschper -v
  - htmlproofer public --check-html --disable-external
