matrix:
  include:
    - name: "Hugo Min Version"
      env:
        - latest=false
    - name: "Hugo Latest Version"
      env:
        - latest=true


env:
  global:
    - minVer=0.48
    - HUGO_THEME=hugo-chaschper

install:
  - rm -rf public || exit 0
  - mkdir ~/_bin
  - |
    if [ $latest ]; then
      export link=$(curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | grep "/hugo_[0-9]\.[0-9]*_Linux-64bit.tar.gz" | cut -d\" -f4)
    else
      export link="https://github.com/gohugoio/hugo/releases/download/v${minVer}/hugo_${minVer}_Linux-64bit.tar.gz"
    fi
  - echo $link
  - wget $link -O hugo.tgz
  - tar xfv hugo.tgz -C ~/_bin
  - rm hugo.tgz ~/_bin/*.md
  - export PATH=$HOME/_bin:$PATH

script:
  - hugo version
  - cd exampleSite
  - hugo
