name = "Casse-pere"
license = "MIT"
licenselink = "https://github.com/albanleandri/hugo-casse-pere/blob/master/LICENSE.md"
description = "Based on Casper 2, simplified, IndieWeb, Gallery"
homepage = "https://github.com/albanleandri/hugo-casse-pere"
tags = ["blog","pages", "ghost theme", "indieweb", "gallery"]
features = ["indieweb", "matomo"]
min_version=0.41

[author]
  name = "Alban Leandri"
  homepage = "https://albanleandri.com"
  repo = "https://github.com/albanleandri"

[original]
  name = "Casper-Two"
  homepage = "https://github.com/eueung/hugo-casper-two"
  repo = "https://github.com/eueung/hugo-casper-two"
