name = "Chaschper"
license = "MIT"
licenselink = "https://github.com/jcfischer/hugo-chaschper/blob/master/LICENSE.md"
description = "Based on Casper 2, simplified, IndieWeb"
homepage = "https://github.com/jcfischer/hugo-chaschper"
tags = ["blog","pages", "ghost theme", "indieweb", "gallery"]
features = ["indieweb", "matomo"]
min_version=0.31

[author]
  name = "Jens-Christian Fischer"
  homepage = "https:/invisible.ch"

[original]
  name = "Casper-Two"
  homepage = "https://github.com/eueung/hugo-casper-two"
  repo = "https://github.com/eueung/hugo-casper-two"
