baseurl         = "https://example.com"
title           = "Casse-pere - Hugo. Blog"
theme           = [ "hugo-casse-pere" ] # add "matomo" if you want matomo tracking
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
assetDir        = "static"

[author]
    name    = "Alban Leandri"
    nick    = "albanleandri"
    email   = "alban.leandri@gmail.com"
    avatar  = "/img/avatar.jpg"
    description = "Product Manager. Marketer. Engineer"
    website = "https://my-website.com"

[params]
  title       = "My Blog"
  domain      = "albanleandri.com"
  subtitle    = "Hugo. HTML. Blog"
  copyright   = "© 2019"

  cover       = "img/blog-cover.jpg"
  description = "Blog Example"
  metaDescription = ""
  googleAnalytics = ""
  googleTagManager = "GTM-XXXXXXX"
  customCSS = []
  RSSLink = "" # "/post/index.xml" for RSS feed of "post" content type
  showSubcribe = true
  showSearch = false
  showReadingTime = true
  showAuthorSignature = false

  mainSections = ["musings", "music", "code", "art"]

  twitterName = "yourhandle"
  fbName = "yourhandle"
  githubName = "yourhandle"
  linkedinName = "yourhandle"
  keybaseName = "yourhandle"
  flickrName = "yourhandle"


  pageNotFoundTitle = "404 - Page not found"

  googleSiteVerification = "xyzGoogleVerificationCode"
  yandexSiteVerification = "abcYandexSiteVerification"


[permalinks]
  posts = "/:year/:month/:slug/"

[[memu.main]]
  name = "Home"
  url = "/"
  weight = 999

[[menu.main]]
  name = "Musings"
  url = "/categories/musings"
  weight = 200

[[menu.main]]
  name = "Music"
  url = "/categories/music"
  weight = 100

[[menu.main]]
  name = "Code"
  url = "/categories/code"
  weight = 99

[[menu.main]]
  name = "Galleries"
  url = "/galleries"
  weight = 95

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 90


# These are parameters used for indieweb identity. You should set these along
# with the above email/social network parameters.
[params.Indieweb]
    country = "Switzerland"
    city = "Geneva"
    webmention = "albanleandri.com"


# Enable this section for Matomo analytics. You will need to install
# the "matomo" theme and enable it in the themes setting above

# [params.matomo]
#     url = "https://matomo.invisible.ch"
#     id = 1
#
# [params.matomo.track]
#     button = "Enable Analytics"
#     message = "Your visits will be logged."
# [params.matomo.block]
#     button = "Disable Analytics"
#     message = "Your visits will *not* be logged."
