baseurl         = "https://example.com"
title           = "Casse-pere - Hugo. Blog"
theme           = [ "hugo-casse-pere" ]
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true
assetDir        = "static"
enableRobotsTXT = "true"

[sitemap]
  ChangeFreq  = "weekly"
  Priority    = "1"

[author]
    name    = "Alban Leandri"
    nick    = "albanleandri"
    email   = "alban.leandri@gmail.com"
    avatar  = "/img/avatar.jpg"
    description = "Product Manager. Marketer. Engineer"
    website = "https://www.albanleandri.com"

[params]
  domain          = "albanleandri.com"
  title           = "Alban's Blog"
  subtitle        = "Practical… a bit technical… mostly interesting :)"
  copyright       = "AL Production © 2019"
  cover           = "img/blog-cover.jpg"
  logo            = ""
  description     = "This is my personal blog where I share some of the things I've learned, few stories and other information I hope you will enjoy."
  metaDescription = "This is my personal blog where I share some of the things I've learned, few stories and other information I hope you will enjoy."
  pageNotFoundTitle                 = "404 - Page not found"
  googleSiteVerification            = "xxxxxxxxxxxxxxxxxxxxxxx"
  yandexSiteVerification            = "xxxxxxxxxxxxxxxxxxxxxxx"
  googleAnalyticsId                 = ""                # Standalone Google Analytics. Leave empty if you prefer to use GA through Google Tag Manager
  enableGaDebug                     = false             # Will enable GA on localhost too for dev/debug purpose
  customCSS                         = []
  RSSLinkPost                       = "/post/index.xml"
  showSubcribe                      = true
  showSearch                        = false             # Make sure the "domain" parameter is set for site-specific search
  showReadingTime                   = true
  showAuthorSignatureFooterArticle  = true
  showAuthorSignatureFooterCard     = true              # At the bottom of articles or in /post page, card will display the author information
  showTweetAThanks                  = true

# Google Tag Manager
[params.googletagmanager]
containerId = "GTM-XXXXXXX"
# Leave both fields below empty if not using GTM's "Environments" feature
devEnvironment = "&gtm_auth=xxxxxxxxxxxxxx&gtm_preview=env-50&gtm_cookies_win=x"
liveEnvironment = "&gtm_auth=zzzzzzzzzzzzzzzz&gtm_preview=env-1&gtm_cookies_win=x"
track404 = true # If true, a datalayer event will be pushed when a 404 page is hit

[params.pushNotificationSubscribers]
  enable         = true # Do not forget to download the service worker file et add it in the static folder
  siteId         = 'xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxx'

[params.cookieConsentBanner]
  enable         = true
  disclaimerText = "This website is using cookies to track how you interact with it, to give you the most relevant experience. By clicking “Accept”, you consent to the use of ALL the cookies."
  buttonText     = "Accept"
  timeToShowUp   = 1500 # Time in milliseconds for the banner to start showing after DOM is ready
  fadeInOutDuration = 500 # Time in milliseconds for fade-in and fade-out of the banner
  localStorageKey = "cookieConsentStatus"

[params.social]
  twitterName   = "Alban_Leandri"
  fbName        = "alb.lan.5"
  githubName    = "albanleandri"
  linkedinName  = "albanleandri"
  mediumName    = "alban.leandri"
  goodReads     = "108173868"
  keybaseName   = ""
  flickrName    = ""

[permalinks]
  post      = "/post/:slug/"

[[menu.main]]
  name      = "Home"
  url       = "/"
  weight    = 201

[[menu.main]]
  name      = "About"
  url       = "/about/"
  weight    = 196

[params.form] # Contact form
    netlify                 = true
    action                  = "https://formspree.io/xxxxxxx"
    method                  = "POST"
    inputNameName           = "name"
    inputNameLabel          = "Name"
    inputNamePlaceholder    = "Enter your name"
    inputEmailName          = "email"
    inputEmailLabel         = "Email"
    inputEmailPlaceholder   = "Enter a valid email"
    inputMsgName            = "message"
    inputMsgLabel           = "Write something here"
    inputMsgLength          = 750
    inputSubmitValue        = "Submit"

    
# These are parameters used for indieweb identity. You should set these along
# with the above email/social network parameters.
[params.Indieweb]
    country     = "Switzerland"
    city        = "Geneva"
    webmention  = ""

[privacy]
[privacy.disqus]
  disable           = false
[privacy.googleAnalytics]
  anonymizeIP       = false
  disable           = false
  respectDoNotTrack = false
  useSessionStorage = false
[privacy.instagram]
  disable           = false
  simple            = false
[privacy.twitter]
  disable           = false
  enableDNT         = false
  simple            = false
[privacy.vimeo]
  disable           = false
  simple            = false
[privacy.youtube]
  disable           = false
  privacyEnhanced   = false